// Chip Core Module
// Generated by sram-forge
// Chip: gf180mcu_ic_1x1_sram_u8b24k
// 1x1 slot SRAM - 8-bit data, 24KB capacity using 512x8 PDK macros
// This module wraps the SRAM array and provides the core interface
// Connect this to IO pads via chip_top module

module gf180mcu_ic_1x1_sram_u8b24k_core (
    // Power supplies (directly connected to SRAM macros)
    inout  wire                    VDD,
    inout  wire                    VSS,
    // Functional signals
    input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    ce_n,      // Chip enable (active low)
    input  wire                    we_n,      // Write enable (active low)
    input  wire [14:0]       addr,      // Address bus
    input  wire [7:0]        din,       // Data input
    output wire [7:0]        dout       // Data output
);

    // Instantiate SRAM array
    gf180mcu_ic_1x1_sram_u8b24k_sram_array u_sram_array (
        .VDD(VDD),
        .VSS(VSS),
        .clk(clk),
        .rst_n(rst_n),
        .ce_n(ce_n),
        .we_n(we_n),
        .addr(addr),
        .din(din),
        .dout(dout)
    );

endmodule
